using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class Universe {
    public static float G = 0.01f;

    public static string[] starNames = new string[] {"ACAMAR",
                                                    "ACHERNAR",
                                                    "Achird",
                                                    "ACRUX",
                                                    "Acubens",
                                                    "ADARA",
                                                    "Adhafera",
                                                    "Adhil",
                                                    "AGENA",
                                                    "Ain al Rami",
                                                    "Ain",
                                                    "Al Anz",
                                                    "Al Kalb al Rai",
                                                    "Al Minliar al Asad",
                                                    "Al Minliar al Shuja",
                                                    "Aladfar",
                                                    "Alathfar",
                                                    "Albaldah",
                                                    "Albali",
                                                    "ALBIREO",
                                                    "Alchiba",
                                                    "ALCOR",
                                                    "ALCYONE",
                                                    "ALDEBARAN",
                                                    "ALDERAMIN",
                                                    "Aldhibah",
                                                    "Alfecca Meridiana",
                                                    "Alfirk",
                                                    "ALGENIB",
                                                    "ALGIEBA",
                                                    "ALGOL",
                                                    "Algorab",
                                                    "ALHENA",
                                                    "ALIOTH",
                                                    "ALKAID",
                                                    "Alkalurops",
                                                    "Alkes",
                                                    "Alkurhah",
                                                    "ALMAAK",
                                                    "ALNAIR",
                                                    "ALNATH",
                                                    "ALNILAM",
                                                    "ALNITAK",
                                                    "Alniyat",
                                                    "Alniyat",
                                                    "ALPHARD",
                                                    "ALPHEKKA",
                                                    "ALPHERATZ",
                                                    "Alrai",
                                                    "Alrisha",
                                                    "Alsafi",
                                                    "Alsciaukat",
                                                    "ALSHAIN",
                                                    "Alshat",
                                                    "Alsuhail",
                                                    "ALTAIR",
                                                    "Altarf",
                                                    "Alterf",
                                                    "Aludra",
                                                    "Alula Australis",
                                                    "Alula Borealis",
                                                    "Alya",
                                                    "Alzirr",
                                                    "Ancha",
                                                    "Angetenar",
                                                    "ANKAA",
                                                    "Anser",
                                                    "ANTARES",
                                                    "ARCTURUS",
                                                    "Arkab Posterior",
                                                    "Arkab Prior",
                                                    "ARNEB",
                                                    "Arrakis",
                                                    "Ascella",
                                                    "Asellus Australis",
                                                    "Asellus Borealis",
                                                    "Asellus Primus",
                                                    "Asellus Secondus",
                                                    "Asellus Tertius",
                                                    "Asterope",
                                                    "Atik",
                                                    "Atlas",
                                                    "Auva",
                                                    "Avior",
                                                    "Azelfafage",
                                                    "Azha",
                                                    "Azmidiske",
                                                    "Baham",
                                                    "Baten Kaitos",
                                                    "Becrux",
                                                    "Beid",
                                                    "BELLATRIX",
                                                    "BETELGEUSE",
                                                    "Botein",
                                                    "Brachium",
                                                    "CANOPUS",
                                                    "CAPELLA",
                                                    "Caph",
                                                    "CASTOR",
                                                    "Cebalrai",
                                                    "Celaeno",
                                                    "Chara",
                                                    "Chort",
                                                    "COR CAROLI",
                                                    "Cursa",
                                                    "Dabih",
                                                    "Deneb Algedi",
                                                    "Deneb Dulfim",
                                                    "Deneb el Okab",
                                                    "Deneb el Okab",
                                                    "Deneb Kaitos Shemali",
                                                    "DENEB",
                                                    "DENEBOLA",
                                                    "Dheneb",
                                                    "Diadem",
                                                    "DIPHDA",
                                                    "Double Double (7051)",
                                                    "Double Double (7052)",
                                                    "Double Double (7053)",
                                                    "Double Double (7054)",
                                                    "Dschubba",
                                                    "Dsiban",
                                                    "DUBHE",
                                                    "Ed Asich",
                                                    "Electra",
                                                    "ELNATH",
                                                    "ENIF",
                                                    "ETAMIN",
                                                    "FOMALHAUT",
                                                    "Fornacis",
                                                    "Fum al Samakah",
                                                    "Furud",
                                                    "Gacrux",
                                                    "Gianfar",
                                                    "Gienah Cygni",
                                                    "Gienah Ghurab",
                                                    "Gomeisa",
                                                    "Gorgonea Quarta",
                                                    "Gorgonea Secunda",
                                                    "Gorgonea Tertia",
                                                    "Graffias",
                                                    "Grafias",
                                                    "Grumium",
                                                    "HADAR",
                                                    "Haedi",
                                                    "HAMAL",
                                                    "Hassaleh",
                                                    "Head of Hydrus",
                                                    "Heze",
                                                    "Hoedus II",
                                                    "Homam",
                                                    "Hyadum I",
                                                    "Hyadum II",
                                                    "IZAR",
                                                    "Jabbah",
                                                    "Kaffaljidhma",
                                                    "Kajam",
                                                    "KAUS AUSTRALIS",
                                                    "Kaus Borealis",
                                                    "Kaus Meridionalis",
                                                    "Keid",
                                                    "Kitalpha",
                                                    "KOCAB",
                                                    "Kornephoros",
                                                    "Kraz",
                                                    "Kuma",
                                                    "Lesath",
                                                    "Maasym",
                                                    "Maia",
                                                    "Marfak",
                                                    "Marfak",
                                                    "Marfic",
                                                    "Marfik",
                                                    "MARKAB",
                                                    "Matar",
                                                    "Mebsuta",
                                                    "MEGREZ",
                                                    "Meissa",
                                                    "Mekbuda",
                                                    "Menkalinan",
                                                    "MENKAR",
                                                    "Menkar",
                                                    "Menkent",
                                                    "Menkib",
                                                    "MERAK",
                                                    "Merga",
                                                    "Merope",
                                                    "Mesarthim",
                                                    "Metallah",
                                                    "Miaplacidus",
                                                    "Minkar",
                                                    "MINTAKA",
                                                    "MIRA",
                                                    "MIRACH",
                                                    "Miram",
                                                    "MIRPHAK",
                                                    "MIZAR",
                                                    "Mufrid",
                                                    "Muliphen",
                                                    "Murzim",
                                                    "Muscida",
                                                    "Muscida",
                                                    "Muscida",
                                                    "Nair al Saif",
                                                    "Naos",
                                                    "Nash",
                                                    "Nashira",
                                                    "Nekkar",
                                                    "NIHAL",
                                                    "Nodus Secundus",
                                                    "NUNKI",
                                                    "Nusakan",
                                                    "Peacock",
                                                    "PHAD",
                                                    "Phaet",
                                                    "Pherkad Minor",
                                                    "Pherkad",
                                                    "Pleione",
                                                    "Polaris Australis",
                                                    "POLARIS",
                                                    "POLLUX",
                                                    "Porrima",
                                                    "Praecipua",
                                                    "Prima Giedi",
                                                    "PROCYON",
                                                    "Propus",
                                                    "Propus",
                                                    "Propus",
                                                    "Rana",
                                                    "Ras Elased Australis",
                                                    "Ras Elased Borealis",
                                                    "RASALGETHI",
                                                    "RASALHAGUE",
                                                    "Rastaban",
                                                    "REGULUS",
                                                    "Rigel Kentaurus",
                                                    "RIGEL",
                                                    "Rijl al Awwa",
                                                    "Rotanev",
                                                    "Ruchba",
                                                    "Ruchbah",
                                                    "Rukbat",
                                                    "Sabik",
                                                    "Sadalachbia",
                                                    "SADALMELIK",
                                                    "Sadalsuud",
                                                    "Sadr",
                                                    "SAIPH",
                                                    "Salm",
                                                    "Sargas",
                                                    "Sarin",
                                                    "Sceptrum",
                                                    "SCHEAT",
                                                    "Secunda Giedi",
                                                    "Segin",
                                                    "Seginus",
                                                    "Sham",
                                                    "Sharatan",
                                                    "SHAULA",
                                                    "SHEDIR",
                                                    "Sheliak",
                                                    "SIRIUS",
                                                    "Situla",
                                                    "Skat",
                                                    "SPICA",
                                                    "Sterope II",
                                                    "Sualocin",
                                                    "Subra",
                                                    "Suhail al Muhlif",
                                                    "Sulafat",
                                                    "Syrma",
                                                    "Tabit (1543)",
                                                    "Tabit (1544)",
                                                    "Tabit (1552)",
                                                    "Tabit (1570)",
                                                    "Talitha",
                                                    "Tania Australis",
                                                    "Tania Borealis",
                                                    "TARAZED",
                                                    "Taygeta",
                                                    "Tegmen",
                                                    "Tejat Posterior",
                                                    "Terebellum",
                                                    "Terebellum",
                                                    "Terebellum",
                                                    "Terebellum",
                                                    "Thabit",
                                                    "Theemim",
                                                    "THUBAN",
                                                    "Torcularis Septentrionalis",
                                                    "Turais",
                                                    "Tyl",
                                                    "UNUKALHAI",
                                                    "VEGA",
                                                    "VINDEMIATRIX",
                                                    "Wasat",
                                                    "Wezen",
                                                    "Wezn",
                                                    "Yed Posterior",
                                                    "Yed Prior",
                                                    "Yildun",
                                                    "Zaniah",
                                                    "Zaurak",
                                                    "Zavijah",
                                                    "Zibal",
                                                    "Zosma",
                                                    "Zuben Elakrab",
                                                    "Zuben Elakribi",
                                                    "Zuben Elgenubi",
                                                    "Zuben Elschemali"};

    public static string [] planetNames = new string []  {"Actaea",
                                                        "Adrastea",
                                                        "Aegaeon",
                                                        "Aegir",
                                                        "Aitne",
                                                        "Albiorix",
                                                        "Amalthea",
                                                        "Ananke",
                                                        "Anthe",
                                                        "Aoede",
                                                        "Arche",
                                                        "Ariel",
                                                        "Atlas",
                                                        "Autonoe",
                                                        "Bebhionn",
                                                        "Belinda",
                                                        "Bergelmir",
                                                        "Bestla",
                                                        "Bianca",
                                                        "Caliban",
                                                        "Callirrhoe",
                                                        "Callisto",
                                                        "Calypso",
                                                        "Carme",
                                                        "Carpo",
                                                        "Chaldene",
                                                        "Charon",
                                                        "Cordelia",
                                                        "Cressida",
                                                        "Cupid",
                                                        "Cyllene",
                                                        "Daphnis",
                                                        "Deimos",
                                                        "Desdemona",
                                                        "Despina",
                                                        "Dia",
                                                        "Dione",
                                                        "Dysnomia",
                                                        "Eirene",
                                                        "Elara",
                                                        "Enceladus",
                                                        "Epimetheus",
                                                        "Erinome",
                                                        "Erriapus",
                                                        "Ersa",
                                                        "Euanthe",
                                                        "Eukelade",
                                                        "Eupheme",
                                                        "Euporie",
                                                        "Europa",
                                                        "Eurydome",
                                                        "Farbauti",
                                                        "Fenrir",
                                                        "Ferdinand",
                                                        "Fornjot",
                                                        "Francisco",
                                                        "Galatea",
                                                        "Ganymede",
                                                        "Greip",
                                                        "Halimede",
                                                        "Harpalyke",
                                                        "Hati",
                                                        "Hegemone",
                                                        "Helene",
                                                        "Helike",
                                                        "Hermippe",
                                                        "Herse",
                                                        "Hiʻiaka",
                                                        "Himalia",
                                                        "Hippocamp",
                                                        "Hydra",
                                                        "Hyperion",
                                                        "Hyrrokkin",
                                                        "Iapetus",
                                                        "Ijiraq",
                                                        "Io",
                                                        "Iocaste",
                                                        "Isonoe",
                                                        "Janus",
                                                        "Jarnsaxa",
                                                        "Juliet",
                                                        "Kale",
                                                        "Kallichore",
                                                        "Kalyke",
                                                        "Kari",
                                                        "Kerberos",
                                                        "Kiviuq",
                                                        "Kore",
                                                        "Laomedeia",
                                                        "Larissa",
                                                        "Leda",
                                                        "Loge",
                                                        "Lysithea",
                                                        "Mab",
                                                        "Margaret",
                                                        "Megaclite",
                                                        "Methone",
                                                        "Metis",
                                                        "Mimas",
                                                        "Miranda",
                                                        "Mneme",
                                                        "Mundilfari",
                                                        "Naiad",
                                                        "Narvi",
                                                        "Nereid",
                                                        "Neso",
                                                        "Nix",
                                                        "Oberon",
                                                        "Ophelia",
                                                        "Orthosie",
                                                        "Paaliaq",
                                                        "Pallene",
                                                        "Pan",
                                                        "Pandia",
                                                        "Pandora",
                                                        "Pasiphae",
                                                        "Pasithee",
                                                        "Perdita",
                                                        "Philophrosyne",
                                                        "Phobos",
                                                        "Phoebe",
                                                        "Polydeuces",
                                                        "Portia",
                                                        "Praxidike",
                                                        "Prometheus",
                                                        "Prospero",
                                                        "Proteus",
                                                        "Psamathe",
                                                        "Puck",
                                                        "Rhea",
                                                        "Rosalind",
                                                        "S/2003 J 10",
                                                        "S/2003 J 12",
                                                        "S/2003 J 16",
                                                        "S/2003 J 18",
                                                        "S/2003 J 19",
                                                        "S/2003 J 2",
                                                        "S/2003 J 23",
                                                        "S/2003 J 4",
                                                        "S/2003 J 9",
                                                        "S/2004 S 12",
                                                        "S/2004 S 13",
                                                        "S/2004 S 17",
                                                        "S/2004 S 20",
                                                        "S/2004 S 21",
                                                        "S/2004 S 22",
                                                        "S/2004 S 23",
                                                        "S/2004 S 24",
                                                        "S/2004 S 25",
                                                        "S/2004 S 26",
                                                        "S/2004 S 27",
                                                        "S/2004 S 28",
                                                        "S/2004 S 29",
                                                        "S/2004 S 30",
                                                        "S/2004 S 31",
                                                        "S/2004 S 32",
                                                        "S/2004 S 33",
                                                        "S/2004 S 34",
                                                        "S/2004 S 35",
                                                        "S/2004 S 36",
                                                        "S/2004 S 37",
                                                        "S/2004 S 38",
                                                        "S/2004 S 39",
                                                        "S/2004 S 7",
                                                        "S/2006 S 1",
                                                        "S/2006 S 3",
                                                        "S/2007 S 2",
                                                        "S/2007 S 3",
                                                        "S/2009 S 1",
                                                        "S/2010 J 1",
                                                        "S/2010 J 2",
                                                        "S/2011 J 1",
                                                        "S/2011 J 2",
                                                        "S/2015 (136472) 1",
                                                        "S/2016 J 1",
                                                        "S/2017 J 1",
                                                        "S/2017 J 2",
                                                        "S/2017 J 3",
                                                        "S/2017 J 5",
                                                        "S/2017 J 6",
                                                        "S/2017 J 7",
                                                        "S/2017 J 8",
                                                        "S/2017 J 9",
                                                        "Sao",
                                                        "Setebos",
                                                        "Siarnaq",
                                                        "Sinope",
                                                        "Skathi",
                                                        "Skoll",
                                                        "Sponde",
                                                        "Stephano",
                                                        "Styx",
                                                        "Surtur",
                                                        "Suttungr",
                                                        "Sycorax",
                                                        "Tarqeq",
                                                        "Tarvos",
                                                        "Taygete",
                                                        "Telesto",
                                                        "Tethys",
                                                        "Thalassa",
                                                        "Thebe",
                                                        "Thelxinoe",
                                                        "Themisto",
                                                        "Thrymr",
                                                        "Thyone",
                                                        "Titan",
                                                        "Titania",
                                                        "Trinculo",
                                                        "Triton",
                                                        "Umbriel",
                                                        "Valetudo",
                                                        "Vanth",
                                                        "Weywot",
                                                        "Xiangliu",
                                                        "Ymir"};

}
